/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.osmcanada.osvuploadr;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;

/**
 *
 * @author Jamie Nadeau
 */
public class JFMain extends javax.swing.JFrame implements ActionListener {
    private JPInfoBox jib;
    private JMenuBar menuBar;
    private JMenu mFile, mActions,mGeo;
    private JMenuItem mExit,mSetBearing;
    private ResourceBundle r;
    private Locale l;
    
    
    /**
     * Creates new form JFMain
     */
    public JFMain() {
        //initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setSize(640,345);
        this.setTitle("OSVUploadr");
    }
    
    public void showInfoBox(){
        jib.setVisible(true);
        this.setSize(640,495);
        this.pack();
    }
    private void setupMenu(){
        menuBar = new JMenuBar();
        mFile = new JMenu(new String(r.getString("Menu_File").getBytes(), StandardCharsets.UTF_8));
        mActions = new JMenu(new String(r.getString("Menu_Actions").getBytes(), StandardCharsets.UTF_8));
        
        mFile.setVisible(true);       
                
        mExit = new JMenuItem(new String(r.getString("Exit").getBytes(), StandardCharsets.UTF_8));
        mExit.addActionListener(this);
        mFile.add(mExit);
        
        mGeo = new JMenu(new String(r.getString("Menu_Geo").getBytes(), StandardCharsets.UTF_8));
        mActions.add(mGeo);
        
        mSetBearing = new JMenuItem(new String(r.getString("Menu_SetBearing").getBytes(), StandardCharsets.UTF_8));
        mSetBearing.addActionListener(this);
        mGeo.add(mSetBearing);
        
        menuBar.add(mFile);
        menuBar.add(mActions);
        
        this.setJMenuBar(menuBar);
    }
    
    public void hideInfoBox(){
        jib.setVisible(false);
        this.setSize(640,345);
    }
    
    public void setInfoBoxText(String str){
        jib.setProcessingText(str);
    }
    
     public void run() {
                l = Locale.getDefault();
                try{
                    r=ResourceBundle.getBundle("Bundle",l);
                }
                catch(Exception ex){
                    System.out.println(ex.toString());
                }
                System.out.println("Language:" + l.getLanguage() + " Country:" + l.getCountry());                
                
                JPMain jp = new JPMain(l);
                jib=new JPInfoBox(l);
                jp.setVisible(true);
                jib.setVisible(false);
                this.add(jp,BorderLayout.NORTH);
                this.add(jib,BorderLayout.SOUTH);
                setupMenu();
                this.setVisible(true);
                
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        new JFMain().run();
    }

    @Override
    public void actionPerformed(ActionEvent e){
        if(e.getSource().equals(mExit))
        {
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
